### ISSUE TITLE
SHA sums for windows builds do not match

### ISSUE THREAD

**Issue by plattrap** [restic/builder#2]
Unfortunately the zip file format includes the file dates in it, so any other build will have different md5sum.

Perhaps `touch` the windows files before zipping them? e.g. `touch -m -a -t 200001010101 restic_0.7.0_windows_386.exe`

Not sure if timezones affect this too.

**Comment by fd0** [comment]
Hm, having a bad timestamp on the exe file is not so nice, but I can see the problem. Please be aware that this issue does not hinder verifying the binaries: The SHA256SUMS file is just used to assure the zip files (for the Windows binaries) are authentic. Just extract the exe file, run the builder yourself, extract the exe file from the new build then you'll end up with the same binaries (exe files).

**Comment by fd0** [comment]
I've documented the process of verifying windows binaries in the README.
